version: '2'
services:

  test_mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/test/null
      - MONGO_INITDB_ROOT_USERNAME=test_super
      - MONGO_INITDB_ROOT_PASSWORD=stub
      - MONGO_INITDB_DATABASE=test_kkhcfiles
    volumes:
      - ./data/mongo/test_docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:37017:27017
    networks:
      test_kkhc_net:
        aliases:
          - test_db 

  test_server:
    build:
      context: ./
      dockerfile: Test.Dockerfile
    environment:
      - EXPRESS_PORT=3055
      - MONGO_INITDB_ROOT_USERNAME=test_super
      - MONGO_INITDB_ROOT_PASSWORD=stub
      - MONGO_INITDB_DATABASE=test_kkhcfiles
    volumes:
      - ./server:/opt/server/
      - ./test:/opt/test/
      - ./data/test_images:/opt/images/
    ports:
      - 8229-8239:8229-8239
    networks:
      - test_kkhc_net
    links:
      - test_mongo
    working_dir: /opt
    # command: ./test_startup.sh

networks:
  test_kkhc_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      # config:
      # - subnet: 172.27.2.1/16
      #   gateway: 172.27.1.10