version: '2'

services:

  test_server:
    build:
      context: ../
      dockerfile: docker/Integration.Dockerfile
    volumes:
      - /mnt/Twins/KKHC_TEST:/opt/files
    env_file:
      - ./../.env
    ports:
      - 7229-7239:7229-7239
    networks:
      - docker_test_kkhc_net
    links:
      - test_mongo:test_db
    working_dir: /opt
    command: ./test_startup.sh

networks:
  docker_test_kkhc_net:
    external: true
